version: '3.8'

services:
  ipja-dash:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8501:8501"
    networks:
      - pi_default
networks:
  pi_default:
    external: true
